# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_folder', models.CharField(blank=True, max_length=15, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ground_truth', models.IntegerField(default=3)),
                ('model_truth', models.IntegerField(default=3)),
                ('model_max', models.FloatField(default=0.0)),
                ('model_min', models.FloatField(default=0.0)),
                ('model_avg', models.FloatField(default=0.0)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('image_type', models.IntegerField(default=0)),
                ('reviewer1', models.IntegerField(blank=True, null=True)),
                ('reviewer2', models.IntegerField(blank=True, null=True)),
                ('reviewer3', models.IntegerField(blank=True, null=True)),
                ('reviewer4', models.IntegerField(blank=True, null=True)),
                ('reviewer5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image Model',
            },
        ),
        migrations.CreateModel(
            name='ImageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.IntegerField(blank=True, null=True)),
                ('reviewer1', models.IntegerField(blank=True, null=True)),
                ('reviewer2', models.IntegerField(blank=True, null=True)),
                ('reviewer3', models.IntegerField(blank=True, null=True)),
                ('reviewer4', models.IntegerField(blank=True, null=True)),
                ('reviewer5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image Order',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('img_array', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'User Model',
            },
        ),
        migrations.AlterField(
            model_name='annotationdata',
            name='annotation_result',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='annotationdata',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
